# fly.toml app configuration file generated for kollab-backend on 2024-01-13T17:01:48+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kollab-backend"
primary_region = "sin"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
